-- UWAGA, DZIA£A TYLKO DLA TYCH DW”CH (DANE W INNYCH PRZYPADKACH S• èLE WYGENEROWANE I PRAWDOPODONIE ZWR”CI NULL)

SELECT dbo.getStudentsAttendanceRate(8, 4)
SELECT dbo.getStudentsAttendanceRate(8, 2)