SELECT TOP (1000) [module_id]
      ,[module_name]
      ,[type]
      ,[start_date]
      ,[end_date]
      ,[classroom]
      ,[lecturer_id]
      ,[translator_id]
      ,[students_limit]
      ,[single_buy_price]
  FROM [u_tzmuda].[dbo].[showNotStartedModules]
